### PR TITLE
trim() before analyzing options & new tests

### PR DESCRIPTION
**Pull request by Eyal-Shalev**
#7 

Co-authored-by: masnagam <masnagam@gmail.com>

### CODE REVIEW

**Comment by masnagam** [comment]
@Eyal-Shalev [v1.0.5](https://github.com/Eyal-Shalev/docopt.js/tree/v1.0.5
) seems not to include this PR.
Would you confirm that and create a new tag?

**Comment by Eyal-Shalev** [comment]
Oops, I'll fix it in a few hours 😅

**Comment by Eyal-Shalev** [comment]
@masnagam v1.0.6 contains this PR

**Comment by masnagam** [comment]
@Eyal-Shalev Thank you!  I confirmed it works fine.

**Pull request merged**
